services:
  teen_up_fe:
    container_name: teen_up_fe
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3001"
    env_file:
      - .env
    restart: unless-stopped

  teen_up_be:
    container_name: teen_up_be
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
